### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by johnbager** [yashkolli/Video-Summarization-Using-Attention#2]
Could you provide your datasets?

**Comment by yashkolli** [comment]
Please refer to the following link. You can find the datasets there. 

https://github.com/KaiyangZhou/vsumm-reinforce/issues/24

**Comment by johnbager** [comment]
so which script can i follow to detail with the data?&nbsp;
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月25日(星期天) 中午1:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yashkolli/Video-Summarization-Using-Attention] Datasets (#2)





 
Please refer to the following link. You can find the datasets there.
 
KaiyangZhou/vsumm-reinforce#24

**Comment by yashkolli** [comment]
This is the readme file for the dataset.

https://github.com/KaiyangZhou/vsumm-reinforce/issues/1#issuecomment-363496750
