### ISSUE TITLE
Has anyone succeeded in using this project to train model?

### ISSUE THREAD

**Issue by chibexme** [yashkolli/Video-Summarization-Using-Attention#4]
I will like to know how to train model with summe or tvsum dataset.

**Comment by yashkolli** [comment]
Hey! Try to use the TVSum preprocessed dataset linked in the readme file. That along with the code in the repository should train your model without any errors.

**Comment by chibexme** [comment]
@yashkolli Thank you so much, the train succeeded with the provided dataset on the readme file
