### ISSUE TITLE
Procedures for genenerating video summary

### ISSUE THREAD

**Issue by chibexme** [yashkolli/Video-Summarization-Using-Attention#5]
@yashkolli kindly help with the procedures and the necessary data for generating video summarization for an input video. 

Thanks in advance.

**Comment by chibexme** [comment]
Where can I get ydata-tvsum50-anno.tsv and ydata-tvsum50.mat? that is needed for summariztion.

**Comment by yashkolli** [comment]
http://people.csail.mit.edu/yalesong/tvsum

**Comment by chibexme** [comment]
Thank you @yashkolli
